service: micromanagement-bot
frameworkVersion: "4"
provider:
  name: aws
  runtime: provided.al2
  region: ap-northeast-1
  stage: dev
  deploymentBucket:
    name: micromanagement-bot-deployments-${self:provider.stage}
    serverSideEncryption: AES256
  ecr:
    images:
      micromanagement-bot:
        path: .
        repositoryName: micromanagement-bot-${self:provider.stage}
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    TASK_LIST_ID: ${env:TASK_LIST_ID}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    REDIRECT_URI: ${env:REDIRECT_URI}
    REFRESH_TOKEN: ${env:REFRESH_TOKEN}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    SLACK_USER_ID: ${env:SLACK_USER_ID}

functions:
  slack:
    image: 
      name: micromanagement-bot
    events:
      - http:
          path: slack/events
          method: post
  dailyReport:
    image:
      name: micromanagement-bot
    events:
      - schedule:
          name: dailyReportSchedule
          description: '毎日20時に実行される定期タスク（日本時間）'
          # UTC 11:00 = 日本時間 20:00
          rate: cron(0 11 * * ? *)
          enabled: true
          input:
            eventType: dailyReport

plugins:
  - serverless-offline
