service: micromanagement-bot
frameworkVersion: "4"
provider:
  name: aws
  runtime: provided.al2
  profile: serverless-servicename-agent
  region: ap-northeast-1
  stage: dev
  ecr:
    images:
      micromanagement-bot:
        path: .
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    TASK_LIST_ID: ${env:TASK_LIST_ID}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    REDIRECT_URI: ${env:REDIRECT_URI}
    REFRESH_TOKEN: ${env:REFRESH_TOKEN}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    SLACK_USER_ID: ${env:SLACK_USER_ID}

functions:
  slack:
    image: 
      name: micromanagement-bot
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
