AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to deploy CloudFormation template'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization name
    Default: YourGitHubOrgName
  
  RepositoryName:
    Type: String
    Description: GitHub repository name
    Default: micromanagement-bot
  
  OIDCProviderArn:
    Type: String
    Description: ARN of the GitHub OIDC provider
    Default: arn:aws:iam::ACCOUNT_ID:oidc-provider/token.actions.githubusercontent.com

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsServerlessDeployRole
      Description: Role for GitHub Actions to deploy CloudFormation template
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/Admin
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECRPermissionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # ECRアクセス - コンテナイメージの管理（必要最小限）
              - Effect: Allow
                Action:
                  - ecr:CreateRepository
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource:
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/micromanagement-bot-*
              
              # ECR認証トークン取得（リソース制限なし）
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
        
        - PolicyName: CloudFormationDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudFormationアクセス - スタック操作
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeChangeSet
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/micromanagement-bot-*/*
              
              # CloudFormationアクセス - 変更セット
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeChangeSet
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:changeSet/*
              
              # S3アクセス - デプロイアーティファクト用
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::micromanagement-bot-deployments-*
                  - !Sub arn:aws:s3:::micromanagement-bot-deployments-*/*
              
              # Lambdaアクセス
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:GetPolicy
                Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:micromanagement-bot-*-*
              
              # API Gatewayアクセス
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                  - apigateway:PATCH
                Resource:
                  - !Sub arn:aws:apigateway:${AWS::Region}::/apis
                  - !Sub arn:aws:apigateway:${AWS::Region}::/apis/*
                  - !Sub arn:aws:apigateway:${AWS::Region}::/stages/*
                  - !Sub arn:aws:apigateway:${AWS::Region}::/integrations/*
                  - !Sub arn:aws:apigateway:${AWS::Region}::/routes/*
              
              # EventBridgeアクセス - スケジュールイベント用
              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:DescribeRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                Resource:
                  - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/dailyReportSchedule
              
              # CloudWatchログアクセス
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/micromanagement-bot-*-*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/micromanagement-bot-*-*:*
              
              # IAMロール管理（Lambda実行ロール用）
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/micromanagement-bot-*-lambda-role

Outputs:
  RoleARN:
    Description: ARN of the IAM Role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
