name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCLOUD_AUTH }}"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Configure docker for artifact registry
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/micromanagement-bot/production:$GITHUB_SHA . 

    - name: Push to Artifact Registry
      run: |
        docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/micromanagement-bot/production:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy micromanagement-bot --image asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/micromanagement-bot/production:$GITHUB_SHA --platform managed --region asia-northeast1 --allow-unauthenticated --max-instances 1 --port 3000
